version: "3.8"

services:
  backend:
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MACHINE_NAME=S4V-THANGLE
      - MONGODB_URL=mongodb://mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - nft4c-net
  
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nft4c-net
volumes:
  mongo-data:
networks:
  nft4c-net:
