version: "3.8"

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MACHINE_NAME=S4V-THANGLE
      - MONGODB_URL=mongodb://mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo-data:
